version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"  # Use PORT if set, otherwise default to 8000
    env_file:
      - .env
    depends_on:
      - db
    command: ["gunicorn", "--bind", "0.0.0.0:${PORT:-8000}", "main:app"]  # Use --bind instead of -b
    container_name: redink

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: